
# Download the SDK and assign current directory.
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# Copy csproj configuration and restore data layers. 
COPY *.csproj .
RUN dotnet restore
COPY . .

# Build application
WORKDIR "/src/."
RUN dotnet build "Api.csproj" -c Release -o /app/build

# Publish application
FROM build as publish
RUN dotnet publish "Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Copy required sysadmin files and start application.
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=publish /app/publish ./

COPY ./Sysadmin ./Sysadmin
RUN bash ./Sysadmin/Docker/Setup

ENTRYPOINT ["bash", "./Sysadmin/Docker/Start"]
