using System.Reflection;
using App.Core.Domain.Mappers;
using App.Core.Domain.Mappers.Entity;
using App.Core.Domain.Startup;
using App.Core.Infrastructure.Mappers;

namespace App.Core.Infrastructure.Startup.Helpers.Generators;

/// <summary>
/// Currently only works for entityMapper, needs some refactoring to allow for multi-generic class
/// </summary>
[StartupSetupOptions]
public class SetupAutoGeneratedMappers : IStartupSetup
{
    private struct GeneratorType 
    {
        public Type Attribute {get; set;}
        public Type Interface {get; set;}
        public Type Implementation {get; set;}
    }

    private readonly GeneratorType[] generatorTypes = new GeneratorType[]{
            new(){
                Attribute = typeof(SetEntityRemapperAttribute),
                Interface = typeof(IEntityRemapper<,>),
                Implementation = typeof(EntityRemapper<,>)
            }
    };


    public void ConfigureService(IServiceCollection services, IEnumerable<Type> assemblyTypes)
    {
        foreach (GeneratorType generatorType in this.generatorTypes)
        {
            if (typeof(ISetEntityRemapperAttribute).IsAssignableFrom(generatorType.Attribute))
            {
                foreach (Type assemblyType in assemblyTypes.Where(t => t.GetCustomAttribute(generatorType.Attribute) is not null))
                {
                    Attribute? attribute = assemblyType.GetCustomAttribute(generatorType.Attribute);

                    if (attribute is ISetEntityRemapperAttribute generatorInfo)
                    {
                        Type generatorInterface = generatorType.Interface.MakeGenericType(assemblyType, generatorInfo.MapToType);
                        Type generatorMapper = generatorType.Implementation.MakeGenericType(assemblyType, generatorInfo.MapToType);

                        services.AddSingleton(generatorInterface, generatorMapper);
                    }
                }
            }
        }
    }
}