# !TODO: Move cert loading to dockerfile

version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Sysadmin/DockerFile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # AuthServer__Authority: https://localhost:443
      # ASPNETCORE_HTTP_PORT: 8000
      # ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Sysadmin/Certs/mycert.pfx
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: 12345