version: '3'
services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "443:443"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AuthServer__Authority: https://localhost:443
    expose:
      - 443
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: 12345